language: android

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - platform-tools
    - extra-android-support # because I'm use support library
    - extra-android-m2repository # because I'm use support library
  licenses:
    - '.+'
language: java

jdk:
  - oraclejdk8

install: true

before_script:
    - chmod +x ./gradlew

script:
  - ./gradlew check
  - ./gradlew build cobertura coveralls
	
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew cobertura coveralls
